# Generated by Django 5.2.7 on 2025-11-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('products', 'Products List'), ('marketing', 'Marketing List'), ('orders', 'Order List'), ('media', 'Media Plans'), ('offers', 'Offer Pricing SKUs'), ('clients', 'Clients'), ('suppliers', 'Suppliers'), ('support', 'Customer Support'), ('sales', 'Sales Reports'), ('finance', 'Finance & Accounting')], max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
